Menambahkan tugas praktikum 5
Praktikum-PBW/4a-tugas-5-anandito-rafi-putra pull request #1
Opened 2022-03-11 13:41 UTC by anandito22

acc kang

2022-03-16 15:51 UTC, anandito22 commented
acc kang

2022-03-18 08:58 UTC, budistwn15 requested changes
Yang diupload kode nya dengan ekstensi .html, .css, .js atau semua ekstensi gambar. Tidak boleh upload dengan ekstensi .rar atau .zip

2022-05-10 05:40 UTC, anandito22 commented
tugas5

2022-05-10 05:43 UTC, budistwn15 approved these changes

2022-05-10 05:43 UTC, merged